[package]
name = "redis-event-bus-task-notifications"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
qubit-event-bus-redis = { path = "../../..", default-features = false, features = ["sync", "async", "discovery"] }
qubit-event-bus = { version = "0.20.0", path = "../../../../rs-event-bus", default-features = false, features = ["discovery"] }
qubit-task = { path = "../../../../rs-task", features = ["sqlite", "event-bus"] }
qubit-codec = { path = "../../../../rs-codec" }
tempfile = "3"
qubit-id = "0.7"
qubit-model-id = { version = "0.1", path = "../../../../rs-model-metadata/model-id" }
qubit-spi = "0.13"
serde_json = "1"
tokio = { version = "1.53", features = ["rt-multi-thread", "macros"] }

[patch.crates-io]
qubit-event-bus = { version = "0.20.0", path = "../../../../rs-event-bus" }
