[package]
name = "redis-event-bus-business-consumer"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
qubit-event-bus = { version = "0.20", path = "../../../../rs-event-bus", default-features = false, features = ["discovery"] }
qubit-event-bus-redis = { path = "../../..", default-features = false, features = ["sync", "discovery"] }
qubit-spi = "0.13"
